version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64   
    ldflags:
      - -s -w -X github.com/eliran89c/klama/cmd.version={{.Version}} -X github.com/eliran89c/klama/cmd.arch={{.Arch}}

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip

changelog:
  sort: asc
  filters:
    include:
      - "^feat:"
      - "^fix:"
      - "^chore:"
      - "^BREAKING CHANGE:"


release:
  github:
    owner: eliran89c
    name: klama

brews:
  -
    # Name of the recipe
    name: klama

    # GitHub repository to push the formula to
    repository:
      owner: eliran89c
      name: homebrew-tap

    # Git author used to commit to the repository.
    commit_author:
      name: Eliran Cohen
      email: eliran89c@gmail.com

    # Folder inside the repository to put the formula.
    directory: Formula

    # Your app's homepage.
    homepage: "https://github.com/eliran89c/klama"

    # app description.
    description: "AI-powered CLI assistant for troubleshooting DevOps-related issues."

    # Setting this will prevent goreleaser to actually try to commit the updated
    # formula - instead, the formula file will be stored on the dist folder only,
    # leaving the responsibility of publishing it to the user.
    # Default is false.
    skip_upload: false

    # So you can `brew test` your formula.
    test: |
      system "#{bin}/klama version"
    # Custom install script for brew.
    # Default is 'bin.install "program"'.
    install: |
      bin.install "klama"