name: Run tests

on:
  pull_request:
    branches: 
      - main
    paths:
      - '**.go'
      - 'go.mod'
      - 'go.sum'
      - '.github/workflows/build-test.yaml'

env:
  CGO_ENABLED: 0

jobs:
  fmt_and_vet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - name: Check vet
        run: go vet ./...

      - name: Check fmt
        run: |
          go fmt ./...
          if [[ -z "$(git status --porcelain)" ]]; then
            echo "Formatting is consistent with 'go fmt'."
          else
            echo "Run 'go fmt ./...' to automatically apply standard Go style to all packages."
            git status --porcelain
            exit 1
          fi

  unit_tests:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        go_version: ['1.22']
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go_version }}

      - name: Build code
        run: go build -v ./...

      - name: Running unit tests
        run: go test -v ./...